
/**
 * This file contains methods that produce a profiler map to pass to instanbul
 * from data generated by `instrumentSolidity.js`
 */
const SolidityCoder = require('web3/lib/solidity/coder.js');
const path = require('path');
const keccak = require('keccakjs');
const fs = require('fs');

/**
 * Converts solprofiler event data into an object that can be
 * be passed to instanbul to produce profiler reports.
 * @type {ProfilerMap}
 */
module.exports = class ProfilerMap {

  constructor() {
    this.profiler = {};
    this.assertProfiler = {};
    this.lineTopics = [];
    this.functionTopics = [];
    this.branchTopics = [];
    this.statementTopics = [];
    this.assertPreTopics = [];
    this.assertPostTopics = [];
  }

  /**
   * Initializes a profiler map object for contract instrumented per `info` and located
   * at `canonicalContractPath`
   * @param {Object} info `info = getIntrumentedVersion(contract, fileName, true)`
   * @param {String} canonicalContractPath target file location
   * @return {Object} profiler map with all values set to zero
   */

  addContract(info, canonicalContractPath) {
    this.profiler[canonicalContractPath] = {
      l: {},
      path: canonicalContractPath,
      s: {},
      b: {},
      f: {},
      fnMap: {},
      statementMap: {},
      branchMap: {},
    };
    this.profiler[canonicalContractPath].gas = this.profiler[canonicalContractPath];
    this.assertProfiler[canonicalContractPath] = { };

    info.runnableLines.forEach((item, idx) => {
      this.profiler[canonicalContractPath].l[info.runnableLines[idx]] = 0;
    });
    this.profiler[canonicalContractPath].fnMap = info.fnMap;
    for (let x = 1; x <= Object.keys(info.fnMap).length; x++) {
      this.profiler[canonicalContractPath].f[x] = 0;
    }
    this.profiler[canonicalContractPath].branchMap = info.branchMap;
    for (let x = 1; x <= Object.keys(info.branchMap).length; x++) {
      this.profiler[canonicalContractPath].b[x] = [0, 0];
      this.profiler[canonicalContractPath].gas.b[x] = [[], []];
      this.assertProfiler[canonicalContractPath][x] = {
        preEvents: 0,
        postEvents: 0,
      };
    }
    this.profiler[canonicalContractPath].statementMap = info.statementMap;
    for (let x = 1; x <= Object.keys(info.statementMap).length; x++) {
      this.profiler[canonicalContractPath].s[x] = 0;
    }

    const keccakhex = (x => {
      const hash = new keccak(256); // eslint-disable-line new-cap
      hash.update(x);
      return hash.digest('hex');
    });

    const lineHash = keccakhex('__Profiler' + info.contractName + '(string,uint256,uint256)');
    const fnHash = keccakhex('__FunctionProfiler' + info.contractName + '(string,uint256,uint256)');
    const branchHash = keccakhex('__BranchProfiler' + info.contractName + '(string,uint256,uint256,uint256)');
    const statementHash = keccakhex('__StatementProfiler' + info.contractName + '(string,uint256,uint256)');
    const assertPreHash = keccakhex('__AssertPreProfiler' + info.contractName + '(string,uint256,uint256)');
    const assertPostHash = keccakhex('__AssertPostProfiler' + info.contractName + '(string,uint256,uint256)');

    this.lineTopics.push(lineHash);
    this.functionTopics.push(fnHash);
    this.branchTopics.push(branchHash);
    this.statementTopics.push(statementHash);
    this.assertPreTopics.push(assertPreHash);
    this.assertPostTopics.push(assertPostHash);

    const topics = `${lineHash}\n${fnHash}\n${branchHash}\n${statementHash}\n${assertPreHash}\n${assertPostHash}\n`;
    fs.appendFileSync('./spTopics', topics);
  }

  /**
   * Populates an empty profiler map with values derived from an array of events
   * fired by instrumented contracts as they are tested
   * @param  {Array} events
   * @param  {String} relative path to host contracts eg: './../contracts'
   * @return {Object} profiler map.
   */
  generate(events, pathPrefix) {
    for (let idx = 0; idx < events.length; idx++) {
      const event = JSON.parse(events[idx]);

      if (event.topics.filter(t => this.lineTopics.indexOf(t) >= 0).length > 0) {
        const data = SolidityCoder.decodeParams(['string', 'uint256', 'uint256'], event.data.replace('0x', ''));
        const canonicalContractPath = data[0];
        this.profiler[canonicalContractPath].l[data[1].toNumber()] += 1;
        this.gasProfiler[canonicalContractPath].gas.l[data[1].toNumber()] =
          (this.gasProfiler[canonicalContractPath].gas.l[data[1].toNumber()] || []).concat([data[2].toNumber()])
      } else if (event.topics.filter(t => this.functionTopics.indexOf(t) >= 0).length > 0) {
        const data = SolidityCoder.decodeParams(['string', 'uint256', 'uint256'], event.data.replace('0x', ''));
        const canonicalContractPath = data[0];
        this.profiler[canonicalContractPath].f[data[1].toNumber()] += 1;
        this.gasProfiler[canonicalContractPath].gas.f[data[1].toNumber()] =
          (this.gasProfiler[canonicalContractPath].gas.f[data[1].toNumber()] || []).concat([data[2].toNumber()])
      } else if (event.topics.filter(t => this.branchTopics.indexOf(t) >= 0).length > 0) {
        const data = SolidityCoder.decodeParams(['string', 'uint256', 'uint256', 'uint256'], event.data.replace('0x', ''));
        const canonicalContractPath = data[0];
        this.profiler[canonicalContractPath].b[data[1].toNumber()][data[2].toNumber()] += 1;
        this.gasProfiler[canonicalContractPath].gas.b[data[1].toNumber()] =
          (this.gasProfiler[canonicalContractPath].gas.b[data[1].toNumber()] || []).concat([data[3].toNumber()])
      } else if (event.topics.filter(t => this.statementTopics.indexOf(t) >= 0).length > 0) {
        const data = SolidityCoder.decodeParams(['string', 'uint256', 'uint256'], event.data.replace('0x', ''));
        const canonicalContractPath = data[0];
        this.profiler[canonicalContractPath].s[data[1].toNumber()] += 1;
        this.gasProfiler[canonicalContractPath].gas.s[data[1].toNumber()] =
          (this.gasProfiler[canonicalContractPath].gas.s[data[1].toNumber()] || []).concat([data[2].toNumber()])
      } else if (event.topics.filter(t => this.assertPreTopics.indexOf(t) >= 0).length > 0) {
        const data = SolidityCoder.decodeParams(['string', 'uint256', 'uint256'], event.data.replace('0x', ''));
        const canonicalContractPath = data[0];
        this.assertProfiler[canonicalContractPath][data[1].toNumber()].preEvents += 1;
      } else if (event.topics.filter(t => this.assertPostTopics.indexOf(t) >= 0).length > 0) {
        const data = SolidityCoder.decodeParams(['string', 'uint256', 'uint256'], event.data.replace('0x', ''));
        const canonicalContractPath = data[0];
        this.assertProfiler[canonicalContractPath][data[1].toNumber()].postEvents += 1;
      }
    }
    // Finally, interpret the assert pre/post events
    Object.keys(this.assertProfiler).forEach(contractPath => {
      const contract = this.profiler[contractPath];
      for (let i = 1; i <= Object.keys(contract.b).length; i++) {
        const branch = this.assertProfiler[contractPath][i];
        if (branch.preEvents > 0) {
          // Then it was an assert branch.
          this.profiler[contractPath].b[i] = [branch.postEvents, branch.preEvents - branch.postEvents];
        }
      }
    });
    return Object.assign({}, this.profiler);
  }
};
